[package]
name = "node_sequential_99_dense_297_biasadd_readvariableop_0"
version = "0.1.0"
edition = "2023_10"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "8ff7389" } 
[lib]
sierra-text = true